export enum Status {
  ACTIVE = 'ACTIVE',
  BLOCKED = 'BLOCKED',
  DISABLED  = 'DISABLED',
  DEACTIVATED  = 'DEACTIVATED',
}

export enum UserStatus {
  CREATED = 'CREATED',
  WAITING_VALIDATION = 'AWAITING_EMAIL_VERIFICATION',
  ACTIVE = 'ACTIVE',
  BLOCKED = 'DISABLED',
  PASSWORD_VALIDATION = 'AWAITING_PASSWORD',
}
